package com.lawra.backend.service;

import com.lawra.backend.dto.AuditLogDTO;
import com.lawra.backend.dto.AuditLogExportRequestDTO;
import com.lawra.backend.dto.AuditLogSearchRequestDTO;
import com.lawra.backend.mapper.AuditLogMapper;
import com.lawra.backend.model.AuditLog;
import com.lawra.backend.repository.AuditLogRepository;
import lombok.RequiredArgsConstructor;
import org.openpdf.text.Document;
import org.openpdf.text.Element;
import org.openpdf.text.Paragraph;
import org.openpdf.text.Font;
import org.openpdf.text.FontFactory;
import org.openpdf.text.pdf.PdfPCell;
import org.openpdf.text.pdf.PdfPTable;
import org.openpdf.text.pdf.PdfWriter;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
@RequiredArgsConstructor
public class AuditLogService {

    private static final int LIST_PREVIEW_MAX_CHARS = 800;
    private static final int EXPORT_PREVIEW_MAX_CHARS = 8000;
    private static final int MAX_HARD_EXPORT_ROWS = 50_000;

    private final AuditLogRepository auditLogRepository;
    private final AuditLogMapper auditLogMapper;

    public Page<AuditLogDTO> search(AuditLogSearchRequestDTO request, Pageable pageable) {
        Page<AuditLog> page = auditLogRepository.search(
                request.getFrom(),
                request.getTo(),
                request.getAction(),
                request.getResourceType(),
                request.getResourceId(),
                request.getActorEmail(),
                pageable
        );

        return page.map(log -> auditLogMapper.toDto(log, LIST_PREVIEW_MAX_CHARS));
    }

    public byte[] exportCsv(AuditLogExportRequestDTO request) {
        List<AuditLogDTO> rows = findForExport(request);

        StringBuilder sb = new StringBuilder();
        // Header
        sb.append(csvEscape("timestamp")).append(",");
        sb.append(csvEscape("actorEmail")).append(",");
        sb.append(csvEscape("actorRole")).append(",");
        sb.append(csvEscape("action")).append(",");
        sb.append(csvEscape("resourceType")).append(",");
        sb.append(csvEscape("resourceId")).append(",");
        sb.append(csvEscape("httpMethod")).append(",");
        sb.append(csvEscape("path")).append(",");
        sb.append(csvEscape("statusCode")).append(",");
        sb.append(csvEscape("beforeStatePreview")).append(",");
        sb.append(csvEscape("afterStatePreview")).append("\n");

        for (AuditLogDTO row : rows) {
            sb.append(csvEscape(asIso(row.getTimestamp()))).append(",");
            sb.append(csvEscape(row.getActorEmail())).append(",");
            sb.append(csvEscape(row.getActorRole())).append(",");
            sb.append(csvEscape(row.getAction())).append(",");
            sb.append(csvEscape(row.getResourceType())).append(",");
            sb.append(csvEscape(row.getResourceId())).append(",");
            sb.append(csvEscape(row.getHttpMethod())).append(",");
            sb.append(csvEscape(row.getPath())).append(",");
            sb.append(csvEscape(row.getStatusCode() == null ? "" : String.valueOf(row.getStatusCode()))).append(",");
            sb.append(csvEscape(row.getBeforeStatePreview())).append(",");
            sb.append(csvEscape(row.getAfterStatePreview())).append("\n");
        }

        return sb.toString().getBytes(StandardCharsets.UTF_8);
    }

    public byte[] exportPdf(AuditLogExportRequestDTO request) {
        List<AuditLogDTO> rows = findForExport(request);

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, baos);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 8);

            document.add(new Paragraph("Lawra Audit Logs", titleFont));
            document.add(new Paragraph("Generated by admin export request.", cellFont));
            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(100);
            table.getDefaultCell().setPadding(4f);

            addHeaderCell(table, "Timestamp", cellFont);
            addHeaderCell(table, "Actor", cellFont);
            addHeaderCell(table, "Action", cellFont);
            addHeaderCell(table, "Resource", cellFont);
            addHeaderCell(table, "Effect", cellFont);
            addHeaderCell(table, "Method", cellFont);
            addHeaderCell(table, "Path", cellFont);
            addHeaderCell(table, "Status", cellFont);

            for (AuditLogDTO row : rows) {
                table.addCell(new PdfPCell(new Paragraph(asIso(row.getTimestamp()), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(trim(row.getActorEmail(), 35), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(trim(row.getAction(), 30), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(formatResource(row), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(trim(row.getAfterStatePreview(), 60), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(trim(row.getHttpMethod(), 10), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(trim(row.getPath(), 40), cellFont)));
                table.addCell(new PdfPCell(new Paragraph(row.getStatusCode() == null ? "-" : String.valueOf(row.getStatusCode()), cellFont)));
            }

            document.add(table);
            document.close();

            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF export", e);
        }
    }

    private List<AuditLogDTO> findForExport(AuditLogExportRequestDTO request) {
        int maxRows = request.getMaxRows() == null ? 10_000 : request.getMaxRows();
        maxRows = Math.max(1, Math.min(maxRows, MAX_HARD_EXPORT_ROWS));

        Pageable pageable = PageRequest.of(0, maxRows);
        Page<AuditLog> page = auditLogRepository.searchExport(
                request.getFrom(),
                request.getTo(),
                request.getAction(),
                request.getResourceType(),
                request.getResourceId(),
                request.getActorEmail(),
                pageable
        );

        return page.getContent().stream()
                .map(log -> auditLogMapper.toDto(log, EXPORT_PREVIEW_MAX_CHARS))
                .toList();
    }

    private static void addHeaderCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(text, font));
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        table.addCell(cell);
    }

    private static String csvEscape(String value) {
        if (value == null) return "";
        String s = value.replace("\"", "\"\"");
        boolean needsQuotes = s.contains(",") || s.contains("\"") || s.contains("\n") || s.contains("\r");
        return needsQuotes ? "\"" + s + "\"" : s;
    }

    private static String asIso(java.time.LocalDateTime dt) {
        if (dt == null) return "";
        return dt.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
    }

    private static String trim(String value, int maxChars) {
        if (value == null) return "-";
        if (maxChars <= 0) return "-";
        if (value.length() <= maxChars) return value;
        return value.substring(0, maxChars) + "...";
    }

    private static String formatResource(AuditLogDTO row) {
        String type = row.getResourceType() == null ? "-" : row.getResourceType();
        String id = row.getResourceId() == null ? "-" : row.getResourceId();
        return type + ":" + id;
    }
}

